config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :blog_posts
  # Defines the root path route ("/")
  # root "articles#index"
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def isDraft?
    published_at.nil?
  end

  def isPublished?
    published_at? && published_at <= Time.current
  end

  def isScheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, except: [:index, :create, :new]

  def index
    @blog_posts = user_signed_in? ? BlogPost.all.sorted : BlogPost.published.sorted
  end

  def show 
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def destroy 
    @blog_post.destroy
    redirect_to root_path
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end
  

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
	<div>
		<% if form.object.errors.any? %>
			<div>
				<% form.object.errors.full_messages.each do |message| %>
					<div><%= message %> </div>
				<% end %>
			</div>
		<% end %>
	</div>
	<div>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</div>
	<div>
		<%= form.label :body %>
		<%= form.text_area :body %>
	</div>
	<div>
		<%= form.label :published_at %>
		<%= form.datetime_select :published_at, include_blank: true%>
	</div>
	<%= form.submit %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>New Blog Post <%= @blog_post.id %> </h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>
<%= button_to "delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure you?"} %>

app/views/blog_posts/index.html.erb
<% @blog_posts.each do |blog_post| %>
	<div>
		<h2><%= link_to blog_post.title, blog_post %></h2>
		<% if user_signed_in? %>
			<% if blog_post.isDraft? %>
				<div class="p-2 rounded bg-gray-200 text-gray-900">Draft</div>
			<% elsif blog_post.isPublished? %>
				<div class="p-2 rounded bg-green-200 text-gray-900">Published</div>
			<% elsif blog_post.isScheduled? %>
				<div class="p-2 rounded bg-red-200 text-gray-900">Scheduled</div>
			<% end %>
		<% end %>
		<%= blog_post.body %>
	</div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path if user_signed_in? %>
<h1><%=@blog_post.title%> </h1>
<p><%=@blog_post.body%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Blog</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_importmap_tags %>
	</head>
	<body class="prose mx-auto">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
		<div>
			<%= link_to "Home", root_path %>
			<% if user_signed_in? %>
				<%= link_to "New", new_blog_post_path %>
				<%= button_to "Log out", destroy_user_session_path, method: :delete %>
				<%# else %>
				<%#= link_to "Login", new_user_session_path %>
				<%#= link_to "Sign Up", new_user_registration_path %>
			<% end %>
		</div>
		<%= yield %>
	</body>
</html>